# Sử dụng image base cho xây dựng React app
FROM node:18.16.1 as build

# Tạo thư mục làm việc
WORKDIR /app/frontend

# Copy package.json và package-lock.json vào thư mục làm việc
COPY package*.json package-lock.json ./
RUN npm i --legacy-peer-deps

# Copy mã nguồn React app
COPY . .

# Build ứng dụng React
RUN npm run build

# Tạo ảnh nginx để chạy ứng dụng build
FROM nginx:alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]